version: '3'

services:
    db:
        restart: unless-stopped
        build:
            context: ./docker/mysql
        volumes:
            - ./db:/var/lib/mysql
        ports:
            - "127.0.0.1:3306:3306"
        environment:
            # TODO: change these values according to project
            - MYSQL_ROOT_PASSWORD=db_password
            - MYSQL_USER=db_user
            - MYSQL_PASSWORD=db_password
            - MYSQL_DATABASE=db_name
            - TZ=Asia/Vladivostok
            - LANG=C.UTF-8
        logging:
            options:
                max-file: "7"
                max-size: "5m"

    php:
        restart: unless-stopped
        build:
            context: ./docker/php
            dockerfile: Dockerfile.test
        volumes:
            - .:/app
        working_dir: /app
        depends_on:
            - db
        logging:
            options:
                max-file: "7"
                max-size: "5m"

    httpd:
        restart: unless-stopped
        build:
            context: ./docker/apache
            dockerfile: Dockerfile.test
        ports:
            - "80:80"
        volumes:
            - .:/app
        depends_on:
            - php
        logging:
            options:
                max-file: "7"
                max-size: "5m"

networks:
    default:
        external:
            name: as-help
